apps/main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.popular_list, name='popular_list'),
    path('shop/', views.product_list, name='product_list'),
    path('shop/<slug:slug>/', views.product_detail, name='product_detail'),
    path('shop/category/<slug:category_slug>/', views.product_list, name='product_list_by_category')
]

config/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("apps.main.urls", namespace="main")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

apps/cart/models.py
from django.db import models

# Create your models here.

apps/main/models.py
from django.db import models
from django.urls import reverse
from django.utils.text import slugify
from decimal import Decimal

class Category(models.Model):
    title = models.CharField(max_length=30, unique=True)
    slug = models.SlugField(max_length=30, unique=True, blank=True)

    class Meta:
        ordering = ['title']
        indexes = [models.Index(fields=["title"])]
        verbose_name = 'category'
        verbose_name_plural = 'categories'
    
    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("main:product_list_by_category", args=[self.slug])
    
    def save(self, *args, **kwargs):
        if not self.slug:
            base_slug = slugify(self.title)
            slug = base_slug
            num = 1
            
            while Category.objects.filter(slug=slug).exclude(pk=self.pk).exists():
                slug=f"{base_slug}-{num}"
                num += 1
            self.slug = slug
        super().save(*args, **kwargs)

class Product(models.Model):
    category = models.ForeignKey(Category, related_name="products", on_delete=models.CASCADE)
    title = models.CharField(max_length=30, unique=True)
    slug = models.SlugField(max_length=30, unique=True, blank=True)
    image = models.ImageField(upload_to="product/main", blank=True)
    description = models.TextField(blank=True)
    available = models.BooleanField(default=True, verbose_name="В наличии")
    price = models.DecimalField(max_digits=10, decimal_places=2)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    discount = models.DecimalField(max_digits=4, decimal_places=2, default=0.00,)

    class Meta:
        ordering = ['title']
        indexes = [
            models.Index(fields=['id', 'slug']),
            models.Index(fields=['title']),
            models.Index(fields=['-created_at']),
        ]
        verbose_name = 'product'
        verbose_name_plural = 'products'
    
    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse("main:product_detail", args=[self.slug])
    
    def save(self, *args, **kwargs):
        if not self.slug:
            base_slug = slugify(self.title)
            slug = base_slug
            num = 1

            while Product.objects.filter(slug=slug).exclude(pk=self.pk).exists():
                slug = f"{base_slug}-{num}"
                num += 1
            self.slug = slug
        super().save(*args, **kwargs)
    
    @property
    def sell_price(self):
        if self.discount:
           return round(self.price - self.price / 100, 2)
        return self.price
    
    # возращает скидку 
    def get_discount_percent(self):
        return round(self.discount, 0)
    
class ProductImage(models.Model):
    product = models.ForeignKey(Product, related_name="images", on_delete=models.CASCADE)
    image = models.ImageField(upload_to="product/gallery", blank=True, null=True, verbose_name="Изображение")
    order = models.PositiveIntegerField(default=0)

    class Meta:
        ordering = ('order',)
        verbose_name = 'Фотография товара'
        verbose_name_plural ='Фотографии товара'
    
    def __str__(self):
        return f"Изображение товара: {self.product.title}"

apps/cart/views.py
from django.shortcuts import render

# Create your views here.

apps/main/views.py
from django.shortcuts import render,redirect, get_object_or_404
from django.core.paginator import Paginator
from .models import *
# from cart.forms import CartAddProductForm


def popular_list(request):
    products = Product.objects.all()
    return render(request, "main/index/index.html", {'products':products})

def product_detail(request, slug):
    product = get_object_or_404(Product, slug=slug)
    # cart_product_form = CartAddProductForm
    return render(request, "main/product/detail.html", {'product': product})

def product_list(request, category_slug=None):
    page_number = request.GET.get('page', 1)
    category = None
    categories = Category.objects.all()
    products = Product.objects.all().select_related("category")

    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    
    paginator = Paginator(products, 10)
    page_obj = paginator.get_page(page_number)

    return render(request, "main/product/list.html", {
            "category": category,
            "categories": categories,
            "products": page_obj.object_list,
            "page_obj": page_obj,
            "category_slug": category_slug,
        },)

apps/main/templates/main/base.html
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock  %}</title>
    <link rel="shortcut icon" href="favicon.ico" type="image/x-icon">
            {# {% comment "" %}bootstarap{% endcomment %} #}
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    {# yourself css  #}
    <link rel="stylesheet" href="{% static 'style/modern-normalize.min.css' %}">
    <link rel="stylesheet" href="{% static 'style/base.css' %}">
</head>
<body>
    <header class="header sticky-top">
        <div class="header-container d-flex ">
            <div class="header-nav pt-4">
                <ul class="header-list d-flex">
                    <li>
                        <a href="{% url 'main:popular_list' %}" class="nav-m m-3">Home</a>
                    </li>
                    <li>
                        <a href="{% url 'main:product_list' %}" class="nav-m m-3">Shop</a>
                    </li>
                </ul>
            </div>
            <div class="header-logo">
                <a href="{% url 'main:product_list' %}"><img src="{% static 'images/qwewqe.png' %}" alt="..." class="heavy-logo"></a>
            </div>
            <div class="header-profile pt-2">
                <div class="cart">
                    <a href="#">
                        <img src="{% static 'images/grob.png' %}" alt=".." class="grob">
                        {% if cart|length > 0 %}
                            <span class="cart-count">
                                {{cart|length }}
                            </span>
                        {% endif %}
                    </a>
                </div>
                {% if user.is_authenticated %}
                    <a href="" class="m-3">Profile</a>
                    <a href="" class="m-3">Logout</a>
                {% else %}
                    <a href="" class="m-3">Login</a>
                    <a href="" class="m-3">Registration</a>
                {% endif %}
            </div>
        </div>
    </header>
    <div class="container mt-3">
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                    {{message }}
                    <button type="button" class="btn-close" data-bs-dismiss="Alert" aira-label="Close"></button>
                </div>
            {% endfor %}
        {% endif %}
    </div>
    <div class="container">
        {% block content %}
        {% endblock content %}
    </div>
    <img src="{% static 'images\frame1.png' %}" alt="..." class="frame1">
    <img src="{% static 'images\frame2.png' %}" alt="..." class="frame2">
    <img src="{% static 'images\frame3.png' %}" alt="..." class="frame3">
    <img src="{% static 'images\frame4.png' %}" alt="..." class="frame4">
    <footer></footer>
    <script src="{% static 'bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    
    {# pagination js #}
    <script>
        document.addEventListener("keydown", function (event) {
            let prev = document.querySelector(".pagination a[rel='prev']");
            let next = document.querySelector(".pagination a[rel='next']");

            if(event.key === "ArrowLeft" && prev){
                window.location.href = prev.href
            }
            if(event.key === "ArrowRight" && next){
                window.location.href = next.href
            }
        })
    </script>
    {# js messages #}
    <script>
        document.addEventListener("DOMContentLoaded", function (){
            const alerts = document.querySelectorAll(".alert")
            alerts.forEach((alert) => {
                setTimeout(() => {
                    const bsAlert = new bootstrap.Alert(alert)
                    bsAlert.close()
                }, 5000)
            })
        })
    </script>
</body>
</html>

apps/main/templates/main/index/index.html
{% extends "main/base.html" %}

{% load static %}

{% block title %}Home{% endblock title %}

{% block content %}
<section class="home d-flex flex-column align-items-center">
    <div class="home-title d-flex flex-column align-items-center">
        <a href="" class="home-btn bm-4">PopularList</a>
    </div>
    <div class="home-recomendation">
        <div class="rec-title mb-4">
            <h2><span>Popular list</span></h2>
        </div>
    </div>
    <div class="cards">
        {% for product in products  %}
            <a href="{{ product.get_absolute_url }}" class="d-flex flex-column align-items-center text-center">
                <img src="{% if product.image %}{{product.image.url}}{% else %}{% static '' %}{% endif %}" alt="..." class="card-img">
                <h3>{{product.title}}</h3>
                <h5 class="{% if product.available %}text-success{% else %}text-danger{% endif %}"> {{ product.available|yesno:"В наличии,Нет в наличии" }} </h5>
                <h5>Description:{{ product.description|linebreaks}}</h5>
                {% if product.discount %}
                    <div class="card-discount d-flex gap-2">
                        <p class="line">${{ product.price }}</p>
                        <p>${{ product.sell_price}}</p>
                    </div>
                {% else %}
                    <p class="price">${{ product.price }}</p>
                {% endif %}
            </a>
        {% endfor %}
    </div>
</section>
{% endblock content %}

apps/main/templates/main/product/detail.html
{% extends "main/base.html" %}

{% load static %}

{% block title %}{{ product.title }}{% endblock title %}

{% block content %}
    <div class="detail-product d-flex">
        <div class="detail-img">
            <img src="{% if product.image %}{{product.image.url}}{% else %}{% static '' %}{% endif %}" alt="" class="detail-image">
        </div>
        <div class="detail-description">
            <h3>{{ product.title}}</h3>
            <h4>Category:{{ product.category }}</h4>
            <h5>Description:{{ product.description|linebreaks}}</h5>
            {% if product.discount %}
                <div class="card-discount d-flex gap-2">
                    <p class="line">${{ product.price}}</p>
                    <p>${{ product.sell_price}}</p>
                </div>
            {% else %}
                <p class="price">${{ product.price}}</p>
            {% endif %}
            <form action="#" method="post" class="qform" >
                {{cart_product_form }}
                {% csrf_token %}
                <button type="button" class="add-to-cart-btn" value="Add to cart"></button>
            </form>
        </div>
    </div>
{% endblock content %}

apps/main/templates/main/product/list.html
{% extends "main/base.html" %}

{% load static %}

{% block title %}Shop{% endblock title %}

{% block content %}
    <div class="lists d-flex">
        <div class="sidebar">
            <h3>Category</h3>
            <ul>
                <li class="{% if not category %}disabled{% endif %}">
                    <a href="{% url 'main:product_list' %}">All</a>
                </li>
                {% for c in categories %}
                    <li class="{% if category and category.slug == c.slug %}selected{% endif %}">
                        <a href="{{ c.get_absolute_url }}">{{ c.title}}</a>
                    </li>
                {% endfor %}
            </ul>
        </div>
        <div class="main">
            <div class="main-title">
                {% if category %}{{ category.title }}{% else %}Product{% endif %}
            </div>
            <div class="product-list">
                <div class="items">
                    {% for product in products %}
                        <div class="item">
                            <a href="{{ product.get_absolute_url }}" class="home-card d-flex flex-column align-items-center text-center" >
                                {% if product.discount %}
                                    <span class="discount-badge">-{{product.get_discount_percent}}%</span>
                                {% endif %}
                                <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static '' %}{% endif %}" alt="{{ product.title}}" class="main-card-image">
                                <h3>{{ product.title }}</h3>
                                <h5 class="{% if product.available %}text-success {% else %}text-danger{% endif %}">{{ product.available|yesno:"В наличии, Нет в наличии"}}</h5>
                                <h5>Description: {{ product.description|linebreaks }}</h5>
                                {% if product.discount %}
                                    <div class="card-discount d-flex flex-column">
                                        <p class="line">${{ product.price }}</p>
                                        <p>${{ product.sell_price}}</p>
                                    </div>
                                {% else %}
                                    <p class="price">${{ product.price}}</p>
                                {% endif %}
                            </a>
                        </div>
                    {% endfor %}
                </div>
            </div>
            <ul class="pagination">
                {# first page #}
                <li class="{% if page_obj.number == 1 %}disabled{% endif %}">
                    <a href="?page=1">First page</a>
                </li>
                {# button previous #}
                <li class="{% if not page_obj.has_previous %}disabled{% endif %}">
                    <a href="{% if page_obj.has_previouse %}?paga={{ page_obj.previous_page_number }}{% endif %}" rel="prev">
                        <i class="fa fa-arrow-left"></i>
                    </a>
                </li>
                {# отбражение 3 страниц #}
                {% for page in page_obj.paginator.page_range %}
                    {% if page >= page_obj.number|add:-2 and page <= page_obj.number|add:2 %}
                        <li class="{% if page_obj.number == page %}active{% endif %}">
                            <a href="?page={{ page }}">{{page}}</a>
                        </li>
                    {% elif page == page_obj.number|add:-3 or page == page_obj.number|add:3 %}
                        <li class="disabled"><span>...</span></li>
                    {% endif %}
                {% endfor %}
                {# next page #}
                <li class="{% if not page_obj.has_next %}disabled{% endif %}">
                    <a href="{% if page_obj.has_next %}?page={{ page_obj.next_page_number }}{% endif %}" rel="next">
                        <i class="fa fa-arrow-right"></i>
                    </a>
                </li>
                {# last page #}
                <li class="{% if page_obj.number == page_obj.paginator.num_pages %}disabled{% endif %}">
                    <a href="?page={{ page_obj.paginator.num_pages}}">Last</a>
                </li>
            </ul>
        </div>
    </div>
{% endblock content %}